### ISSUE TITLE
Add custom parameters

### ISSUE THREAD

**Issue by zheqd** [Mitrichius/WishlistJS#27]
New optional parameter e.g. "properties" to specify custom properties for an item.
Should be a key-value map. Display as a "key: value" list at the bottom of tile 

Example of properties:
`"properties": {
                "size": "M",
                "color": "green"
            }
`

**Comment by Mitrichius** [comment]
Check demo page (desktop and mobile): https://60256b1f975092000741080f--wishlistjs-demo.netlify.app/

Format:
```
"properties": [
    {
        "key": "Type",
        "value": "Plush"
    },
    {
        "key": "Size",
        "value": "Full"
    }
]
```

If it's good, let me know and I'll merge it
